---
permissions: read-all
concurrency:
  cancel-in-progress: true
  group: ${{ github.actor }}
jobs:
  api_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
      - uses: docker://ghcr.io/fluidattacks/makes:22.11
        name: /api/deploy
        with:
          set-safe-directory: /github/workspace
          args: m . /api/deploy prod
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
          STACKHERO_SERVICE_ID: ${{ secrets.STACKHERO_SERVICE_ID }}
          STACKHERO_PASSWORD: ${{ secrets.STACKHERO_PASSWORD }}

  formatBash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
      - uses: docker://ghcr.io/fluidattacks/makes:22.11
        name: /formatBash
        with:
          set-safe-directory: /github/workspace
          args: m . /formatBash
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  formatMarkdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: docker://ghcr.io/fluidattacks/makes:22.11
        name: /formatMarkdown
        with:
          set-safe-directory: /github/workspace
          args: m . /formatMarkdown
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  formatNix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: docker://ghcr.io/fluidattacks/makes:22.11
        name: /formatNix
        with:
          set-safe-directory: /github/workspace
          args: m . /formatNix
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  formatPython:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: docker://ghcr.io/fluidattacks/makes:22.11
        name: /formatPython
        with:
          set-safe-directory: /github/workspace
          args: m . /formatPython
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  lintBash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
      - uses: docker://ghcr.io/fluidattacks/makes:22.11
        name: /lintBash
        with:
          set-safe-directory: /github/workspace
          args: m . /lintBash
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  lintGitCommitMsg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
      - uses: docker://ghcr.io/fluidattacks/makes:22.11
        name: /lintGitCommitMsg
        with:
          set-safe-directory: /github/workspace
          args: m . /lintGitCommitMsg
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  lintGitMailMap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
      - uses: docker://ghcr.io/fluidattacks/makes:22.11
        name: /lintGitMailMap
        with:
          set-safe-directory: /github/workspace
          args: m . /lintGitMailMap
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  lintMarkdown_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: docker://ghcr.io/fluidattacks/makes:22.11
        name: /lintMarkdown/readme
        with:
          set-safe-directory: /github/workspace
          args: m . /lintMarkdown/readme
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  lintNix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: docker://ghcr.io/fluidattacks/makes:22.11
        name: /lintNix
        with:
          set-safe-directory: /github/workspace
          args: m . /lintNix
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  lintPython_module_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: docker://ghcr.io/fluidattacks/makes:22.11
        name: /lintPython/module/api
        with:
          set-safe-directory: /github/workspace
          args: m . /lintPython/module/api
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  lintWithLizard_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: docker://ghcr.io/fluidattacks/makes:22.11
        name: /lintWithLizard/api
        with:
          set-safe-directory: /github/workspace
          args: m . /lintWithLizard/api
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  securePythonWithBandit_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: docker://ghcr.io/fluidattacks/makes:22.11
        name: /securePythonWithBandit/api
        with:
          set-safe-directory: /github/workspace
          args: m . /securePythonWithBandit/api
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
name: prod
on:
  push:
    branches: [main]
