---
permissions: read-all
concurrency:
  cancel-in-progress: true
  group: ${{ github.actor }}
jobs:
  api_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
        with:
          fetch-depth: 0
      - uses: docker://ghcr.io/fluidattacks/makes/amd64:latest
        name: /api/deploy
        with:
          args: sh -c "chown -R root:root /github/workspace && m . /api/deploy prod"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
          STACKHERO_SERVICE_ID: ${{ secrets.STACKHERO_SERVICE_ID }}
          STACKHERO_PASSWORD: ${{ secrets.STACKHERO_PASSWORD }}

  formatBash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
        with:
          fetch-depth: 0
      - uses: docker://ghcr.io/fluidattacks/makes/amd64:latest
        name: /formatBash
        with:
          args: sh -c "chown -R root:root /github/workspace && m . /formatBash"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  formatMarkdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://ghcr.io/fluidattacks/makes/amd64:latest
        name: /formatMarkdown
        with:
          args: sh -c "chown -R root:root /github/workspace && m . /formatMarkdown"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  formatNix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://ghcr.io/fluidattacks/makes/amd64:latest
        name: /formatNix
        with:
          args: sh -c "chown -R root:root /github/workspace && m . /formatNix"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  formatPython_default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://ghcr.io/fluidattacks/makes/amd64:latest
        name: /formatPython/default
        with:
          args: sh -c "chown -R root:root /github/workspace && m . /formatPython/default"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  lintBash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
        with:
          fetch-depth: 0
      - uses: docker://ghcr.io/fluidattacks/makes/amd64:latest
        name: /lintBash
        with:
          args: sh -c "chown -R root:root /github/workspace && m . /lintBash"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  lintGitCommitMsg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
        with:
          fetch-depth: 0
      - uses: docker://ghcr.io/fluidattacks/makes/amd64:latest
        name: /lintGitCommitMsg
        with:
          args: sh -c "chown -R root:root /github/workspace && m . /lintGitCommitMsg"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  lintGitMailMap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
        with:
          fetch-depth: 0
      - uses: docker://ghcr.io/fluidattacks/makes/amd64:latest
        name: /lintGitMailMap
        with:
          args: sh -c "chown -R root:root /github/workspace && m . /lintGitMailMap"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  lintMarkdown_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://ghcr.io/fluidattacks/makes/amd64:latest
        name: /lintMarkdown/readme
        with:
          args: sh -c "chown -R root:root /github/workspace && m . /lintMarkdown/readme"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  lintNix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://ghcr.io/fluidattacks/makes/amd64:latest
        name: /lintNix
        with:
          args: sh -c "chown -R root:root /github/workspace && m . /lintNix"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  lintPython_module_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://ghcr.io/fluidattacks/makes/amd64:latest
        name: /lintPython/module/api
        with:
          args: sh -c "chown -R root:root /github/workspace && m . /lintPython/module/api"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  lintWithLizard_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://ghcr.io/fluidattacks/makes/amd64:latest
        name: /lintWithLizard/api
        with:
          args: sh -c "chown -R root:root /github/workspace && m . /lintWithLizard/api"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  securePythonWithBandit_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://ghcr.io/fluidattacks/makes/amd64:latest
        name: /securePythonWithBandit/api
        with:
          args: sh -c "chown -R root:root /github/workspace && m . /securePythonWithBandit/api"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
name: prod
on:
  push:
    branches: [main]
